# Generated by Django 2.0.3 on 2018-03-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, unique=True)),
                ('slug', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
